COLLECTION_PATH="${POSTMAN_API_URL}/${POSTMAN_GITHUB_BRANCHES_COLLECTION_UUID}?apikey=${POSTMAN_GITHUB_API_KEY_ANH}"
ENVIRONMENT_PATH="${POSTMAN_API_URL}/environments/${POSTMAN_ENVIRONMENT_GITHUB_PROD}?apikey=${POSTMAN_GITHUB_API_KEY_ANH}"
